raxmlHPC-PTHREADS -T 15 -s amphimedon.phylip -m PROTGAMMALGF -p 12345 -n amphimedon.tre
raxmlHPC-PTHREADS -T 15 -s coeloplana.phylip -m PROTGAMMALGF -p 12345 -n coeloplana.tre
raxmlHPC-PTHREADS -T 15 -s convolutriloba.phylip -m PROTGAMMALGF -p 12345 -n convolutriloba.tre
raxmlHPC-PTHREADS -T 15 -s grantia.phylip -m PROTGAMMALGF -p 12345 -n grantia.tre
raxmlHPC-PTHREADS -T 15 -s lampea.phylip -m PROTGAMMALGF -p 12345 -n lampea.tre
raxmlHPC-PTHREADS -T 15 -s meara.phylip -m PROTGAMMALGF -p 12345 -n meara.tre
raxmlHPC-PTHREADS -T 15 -s mnemiopsis.phylip -m PROTGAMMALGF -p 12345 -n mnemiopsis.tre
raxmlHPC-PTHREADS -T 15 -s plakina.phylip -m PROTGAMMALGF -p 12345 -n plakina.tre
raxmlHPC-PTHREADS -T 15 -s pleraplysilla.phylip -m PROTGAMMALGF -p 12345 -n pleraplysilla.tre
raxmlHPC-PTHREADS -T 15 -s vallicula.phylip -m PROTGAMMALGF -p 12345 -n vallicula.tre
raxmlHPC-PTHREADS -T 15 -s xenoturbella.phylip -m PROTGAMMALGF -p 12345 -n xenoturbella.tre
raxmlHPC-PTHREADS -T 15 -s Lingula.phylip  -m PROTGAMMALGF -p 12345 -n Lingula.tre
raxmlHPC-PTHREADS -T 15 -s Notospermus.phylip  -m PROTGAMMALGF -p 12345 -n Notospermus.tre
raxmlHPC-PTHREADS -T 15 -s Phoronis.phylip  -m PROTGAMMALGF -p 12345 -n Phoronis.tre
raxmlHPC-PTHREADS -T 15 -s Pinctata.phylip  -m PROTGAMMALGF -p 12345 -n Pinctata.tre
raxmlHPC-PTHREADS -T 15 -s Abylopsis.phylip -m PROTGAMMALGF -p 12345 -n Abylopsis.tre
raxmlHPC-PTHREADS -T 15 -s Acanthoscurria.phylip -m PROTGAMMALGF -p 12345 -n Acanthoscurria.tre
raxmlHPC-PTHREADS -T 15 -s Acropora.phylip -m PROTGAMMALGF -p 12345 -n Acropora.tre
raxmlHPC-PTHREADS -T 15 -s Aegina.phylip -m PROTGAMMALGF -p 12345 -n Aegina.tre
raxmlHPC-PTHREADS -T 15 -s Agalma.phylip -m PROTGAMMALGF -p 12345 -n Agalma.tre
raxmlHPC-PTHREADS -T 15 -s Aiptasia.phylip -m PROTGAMMALGF -p 12345 -n Aiptasia.tre
raxmlHPC-PTHREADS -T 15 -s Alatina.phylip -m PROTGAMMALGF -p 12345 -n Alatina.tre
raxmlHPC-PTHREADS -T 15 -s Anemonia.phylip -m PROTGAMMALGF -p 12345 -n Anemonia.tre
raxmlHPC-PTHREADS -T 15 -s Anthopleura.phylip -m PROTGAMMALGF -p 12345 -n Anthopleura.tre
raxmlHPC-PTHREADS -T 15 -s Atolla.phylip -m PROTGAMMALGF -p 12345 -n Atolla.tre
raxmlHPC-PTHREADS -T 15 -s Aurelia.phylip -m PROTGAMMALGF -p 12345 -n Aurelia.tre
raxmlHPC-PTHREADS -T 15 -s Bolocera.phylip -m PROTGAMMALGF -p 12345 -n Bolocera.tre
raxmlHPC-PTHREADS -T 15 -s Brachionus.phylip -m PROTGAMMALGF -p 12345 -n Brachionus.tre
raxmlHPC-PTHREADS -T 15 -s Calvadosia.phylip -m PROTGAMMALGF -p 12345 -n Calvadosia.tre
raxmlHPC-PTHREADS -T 15 -s Capitella.phylip -m PROTGAMMALGF -p 12345 -n Capitella.tre
raxmlHPC-PTHREADS -T 15 -s Cassiopea.phylip -m PROTGAMMALGF -p 12345 -n Cassiopea.tre
raxmlHPC-PTHREADS -T 15 -s Cerianthus.phylip -m PROTGAMMALGF -p 12345 -n Cerianthus.tre
raxmlHPC-PTHREADS -T 15 -s Chironex.phylip -m PROTGAMMALGF -p 12345 -n Chironex.tre
raxmlHPC-PTHREADS -T 15 -s Chrysaora.phylip -m PROTGAMMALGF -p 12345 -n Chrysaora.tre
raxmlHPC-PTHREADS -T 15 -s Clytia.phylip -m PROTGAMMALGF -p 12345 -n Clytia.tre
raxmlHPC-PTHREADS -T 15 -s Corallium.phylip -m PROTGAMMALGF -p 12345 -n Corallium.tre
raxmlHPC-PTHREADS -T 15 -s Corynactis.phylip -m PROTGAMMALGF -p 12345 -n Corynactis.tre
raxmlHPC-PTHREADS -T 15 -s Craseoa.phylip -m PROTGAMMALGF -p 12345 -n Craseoa.tre
raxmlHPC-PTHREADS -T 15 -s Crassostrea.phylip -m PROTGAMMALGF -p 12345 -n Crassostrea.tre
raxmlHPC-PTHREADS -T 15 -s Craspedacusta.phylip -m PROTGAMMALGF -p 12345 -n Craspedacusta.tre
raxmlHPC-PTHREADS -T 15 -s Craterolophus.phylip -m PROTGAMMALGF -p 12345 -n Craterolophus.tre
raxmlHPC-PTHREADS -T 15 -s Ctenactis.phylip -m PROTGAMMALGF -p 12345 -n Ctenactis.tre
raxmlHPC-PTHREADS -T 15 -s Cyanea.phylip -m PROTGAMMALGF -p 12345 -n Cyanea.tre
raxmlHPC-PTHREADS -T 15 -s Daphnia.phylip -m PROTGAMMALGF -p 12345 -n Daphnia.tre
raxmlHPC-PTHREADS -T 15 -s Drosophila.phylip -m PROTGAMMALGF -p 12345 -n Drosophila.tre
raxmlHPC-PTHREADS -T 15 -s Ectopleura.phylip -m PROTGAMMALGF -p 12345 -n Ectopleura.tre
raxmlHPC-PTHREADS -T 15 -s Edwardsiella.phylip -m PROTGAMMALGF -p 12345 -n Edwardsiella.tre
raxmlHPC-PTHREADS -T 15 -s Eunicella_c.phylip -m PROTGAMMALGF -p 12345 -n Eunicella_c.tre
raxmlHPC-PTHREADS -T 15 -s Eunicella_v.phylip -m PROTGAMMALGF -p 12345 -n Eunicella_v.tre
raxmlHPC-PTHREADS -T 15 -s Favia.phylip -m PROTGAMMALGF -p 12345 -n Favia.tre
raxmlHPC-PTHREADS -T 15 -s Gorgonia.phylip -m PROTGAMMALGF -p 12345 -n Gorgonia.tre
raxmlHPC-PTHREADS -T 15 -s Haliclystus_a.phylip -m PROTGAMMALGF -p 12345 -n Haliclystus_a.tre
raxmlHPC-PTHREADS -T 15 -s Haliclystus_s.phylip -m PROTGAMMALGF -p 12345 -n Haliclystus_s.tre
raxmlHPC-PTHREADS -T 15 -s Homo.phylip -m PROTGAMMALGF -p 12345 -n Homo.tre
raxmlHPC-PTHREADS -T 15 -s Hormathia.phylip -m PROTGAMMALGF -p 12345 -n Hormathia.tre
raxmlHPC-PTHREADS -T 15 -s Hydractinia_p.phylip -m PROTGAMMALGF -p 12345 -n Hydractinia_p.tre
raxmlHPC-PTHREADS -T 15 -s Hydractinia_s.phylip -m PROTGAMMALGF -p 12345 -n Hydractinia_s.tre
raxmlHPC-PTHREADS -T 15 -s Hydra_m.phylip -m PROTGAMMALGF -p 12345 -n Hydra_m.tre
raxmlHPC-PTHREADS -T 15 -s Hydra_o.phylip -m PROTGAMMALGF -p 12345 -n Hydra_o.tre
raxmlHPC-PTHREADS -T 15 -s Hydra_vi.phylip -m PROTGAMMALGF -p 12345 -n Hydra_vi.tre
raxmlHPC-PTHREADS -T 15 -s Hydra_vu.phylip -m PROTGAMMALGF -p 12345 -n Hydra_vu.tre
raxmlHPC-PTHREADS -T 15 -s Kudoa.phylip -m PROTGAMMALGF -p 12345 -n Kudoa.tre
raxmlHPC-PTHREADS -T 15 -s Leptogorgia.phylip -m PROTGAMMALGF -p 12345 -n Leptogorgia.tre
raxmlHPC-PTHREADS -T 15 -s Leucernaria.phylip -m PROTGAMMALGF -p 12345 -n Leucernaria.tre
raxmlHPC-PTHREADS -T 15 -s Lobactis.phylip -m PROTGAMMALGF -p 12345 -n Lobactis.tre
raxmlHPC-PTHREADS -T 15 -s Lottia.phylip -m PROTGAMMALGF -p 12345 -n Lottia.tre
raxmlHPC-PTHREADS -T 15 -s Madracis.phylip -m PROTGAMMALGF -p 12345 -n Madracis.tre
raxmlHPC-PTHREADS -T 15 -s Metridium.phylip -m PROTGAMMALGF -p 12345 -n Metridium.tre
raxmlHPC-PTHREADS -T 15 -s Montastraea_c.phylip -m PROTGAMMALGF -p 12345 -n Montastraea_c.tre
raxmlHPC-PTHREADS -T 15 -s Montastraea_f.phylip -m PROTGAMMALGF -p 12345 -n Montastraea_f.tre
raxmlHPC-PTHREADS -T 15 -s Myxobolus_c.phylip -m PROTGAMMALGF -p 12345 -n Myxobolus_c.tre
raxmlHPC-PTHREADS -T 15 -s Myxobolus_p.phylip -m PROTGAMMALGF -p 12345 -n Myxobolus_p.tre
raxmlHPC-PTHREADS -T 15 -s Namomia.phylip -m PROTGAMMALGF -p 12345 -n Namomia.tre
raxmlHPC-PTHREADS -T 15 -s Nematostella.phylip -m PROTGAMMALGF -p 12345 -n Nematostella.tre
raxmlHPC-PTHREADS -T 15 -s Nephthyigorgia.phylip -m PROTGAMMALGF -p 12345 -n Nephthyigorgia.tre
raxmlHPC-PTHREADS -T 15 -s Periphylla.phylip -m PROTGAMMALGF -p 12345 -n Periphylla.tre
raxmlHPC-PTHREADS -T 15 -s Physalia.phylip -m PROTGAMMALGF -p 12345 -n Physalia.tre
raxmlHPC-PTHREADS -T 15 -s Platygyra.phylip -m PROTGAMMALGF -p 12345 -n Platygyra.tre
raxmlHPC-PTHREADS -T 15 -s Pocillopora.phylip -m PROTGAMMALGF -p 12345 -n Pocillopora.tre
raxmlHPC-PTHREADS -T 15 -s Podocoryna.phylip -m PROTGAMMALGF -p 12345 -n Podocoryna.tre
raxmlHPC-PTHREADS -T 15 -s Polypodum.phylip -m PROTGAMMALGF -p 12345 -n Polypodum.tre
raxmlHPC-PTHREADS -T 15 -s Porites.phylip -m PROTGAMMALGF -p 12345 -n Porites.tre
raxmlHPC-PTHREADS -T 15 -s Protopalythoa.phylip -m PROTGAMMALGF -p 12345 -n Protopalythoa.tre
raxmlHPC-PTHREADS -T 15 -s Renilla.phylip -m PROTGAMMALGF -p 12345 -n Renilla.tre
raxmlHPC-PTHREADS -T 15 -s Rhodactis.phylip -m PROTGAMMALGF -p 12345 -n Rhodactis.tre
raxmlHPC-PTHREADS -T 15 -s Ricordea.phylip -m PROTGAMMALGF -p 12345 -n Ricordea.tre
raxmlHPC-PTHREADS -T 15 -s Saccoglossus.phylip -m PROTGAMMALGF -p 12345 -n Saccoglossus.tre
raxmlHPC-PTHREADS -T 15 -s Seriatopora.phylip -m PROTGAMMALGF -p 12345 -n Seriatopora.tre
raxmlHPC-PTHREADS -T 15 -s Stomolophus.phylip -m PROTGAMMALGF -p 12345 -n Stomolophus.tre
raxmlHPC-PTHREADS -T 15 -s Strongylocentrotus.phylip -m PROTGAMMALGF -p 12345 -n Strongylocentrotus.tre
raxmlHPC-PTHREADS -T 15 -s Taeniopygia.phylip -m PROTGAMMALGF -p 12345 -n Taeniopygia.tre
raxmlHPC-PTHREADS -T 15 -s Thelohanellus.phylip -m PROTGAMMALGF -p 12345 -n Thelohanellus.tre
raxmlHPC-PTHREADS -T 15 -s Trichoplax.phylip -m PROTGAMMALGF -p 12345 -n Trichoplax.tre
raxmlHPC-PTHREADS -T 15 -s Tripedalia.phylip -m PROTGAMMALGF -p 12345 -n Tripedalia.tre
raxmlHPC-PTHREADS -T 15 -s Turritopsis.phylip -m PROTGAMMALGF -p 12345 -n Turritopsis.tre
